/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tubespbo;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fathi
 */
public class Laporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Laporan.class.getName());
    private static Connection mysqlconfig;

public static Connection configDB() {
    try {
        String url = "jdbc:mysql://localhost:3306/datapark";
        String user = "root";
        String pass = "";
        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        mysqlconfig = DriverManager.getConnection(url, user, pass);
    } catch (SQLException e) {
        System.err.println("koneksi gagal " + e.getMessage());
    }
    return mysqlconfig;
}

    /**
     * Creates new form Slot
     */
    public Laporan() {
    initComponents();
    loadTable();
    
    javax.swing.Timer timer = new javax.swing.Timer(30000, e -> loadTable());
    timer.start();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("LAPORAN PARKIR");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idTiket", "PlatNomor", "jenis", "waktuMasuk", "waktuKeluar", "durasi", "totalBiaya"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Refresh");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Kembali");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Hapus");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Edit");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int baris = jTable1.getSelectedRow();
    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    String idTiket = jTable1.getValueAt(baris, 0).toString();
    String platNomor = jTable1.getValueAt(baris, 1).toString();
    String jenis = jTable1.getValueAt(baris, 2).toString();

    javax.swing.JTextField tfPlat = new javax.swing.JTextField(platNomor);
    javax.swing.JComboBox<String> cbJenis = new javax.swing.JComboBox<>(new String[]{"motor", "mobil"});
    cbJenis.setSelectedItem(jenis);

    Object[] fields = {
        "Plat Nomor:", tfPlat,
        "Jenis:", cbJenis
    };

    int result = JOptionPane.showConfirmDialog(this, fields,
        "Edit Tiket: " + idTiket, JOptionPane.OK_CANCEL_OPTION);

    if (result == JOptionPane.OK_OPTION) {
        try {
            String platBaru = tfPlat.getText().trim();
            String jenisBaru = cbJenis.getSelectedItem().toString();
            int jumlahRoda = jenisBaru.equalsIgnoreCase("motor") ? 2 : 4;

            if (platBaru.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Plat nomor tidak boleh kosong!");
                return;
            }

            Connection conn = configDB();

            String sqlKendaraan = "UPDATE kendaraan SET jenis = ?, jumlahRoda = ? WHERE platNomor = ?";
            PreparedStatement pstKendaraan = conn.prepareStatement(sqlKendaraan);
            pstKendaraan.setString(1, jenisBaru);
            pstKendaraan.setInt(2, jumlahRoda);
            pstKendaraan.setString(3, platNomor);
            pstKendaraan.execute();

           if (!platBaru.equals(platNomor)) {
                 String cekSql = "SELECT * FROM kendaraan WHERE platNomor = ?";
                PreparedStatement cekPst = conn.prepareStatement(cekSql);
                cekPst.setString(1, platBaru);
                ResultSet cekRs = cekPst.executeQuery();

    if (!cekRs.next()) {
        // Plat belum ada, insert otomatis
        String sqlInsert = "INSERT INTO kendaraan (platNomor, merk, jumlahRoda, jenis) VALUES (?, ?, ?, ?)";
        PreparedStatement pstInsert = conn.prepareStatement(sqlInsert);
        pstInsert.setString(1, platBaru);
        pstInsert.setString(2, "");
        pstInsert.setInt(3, jumlahRoda);
        pstInsert.setString(4, jenisBaru);
        pstInsert.execute();
    }

    String sqlTiket = "UPDATE tiket SET kendaraan = ? WHERE idTiket = ?";
    PreparedStatement pstTiket = conn.prepareStatement(sqlTiket);
    pstTiket.setString(1, platBaru);
    pstTiket.setString(2, idTiket);
    pstTiket.execute();
}

            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            loadTable();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }
    String idTiket = jTable1.getValueAt(baris, 0).toString();
    int konfirmasi = JOptionPane.showConfirmDialog(this, "Hapus tiket " + idTiket + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            Connection conn = configDB();
            String sqlSlot = "UPDATE slotParkir SET status = false WHERE idSlot = (SELECT slot FROM tiket WHERE idTiket = ?)";
            PreparedStatement pstSlot = conn.prepareStatement(sqlSlot);
            pstSlot.setString(1, idTiket);
            pstSlot.execute();

            String sql = "DELETE FROM tiket WHERE idTiket = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idTiket);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
}
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Laporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
    try {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("idTiket");
        model.addColumn("PlatNomor");
        model.addColumn("Jenis");
        model.addColumn("Waktu Masuk");
        model.addColumn("Waktu Keluar");
        model.addColumn("Durasi");
        model.addColumn("Total Biaya");

        Connection conn = configDB();
        String sql = "SELECT t.idTiket, t.kendaraan, k.jenis, t.waktuMasuk, t.waktuKeluar, "
                   + "GREATEST(1, TIMESTAMPDIFF(HOUR, t.waktuMasuk, IFNULL(t.waktuKeluar, NOW()))) as durasi, "
                   + "t.totalBiaya, "
                   + "CASE WHEN t.waktuKeluar IS NULL THEN "
                   + "  GREATEST(1, TIMESTAMPDIFF(HOUR, t.waktuMasuk, NOW())) * IF(k.jenis='Motor', 2000, 4000) "
                   + "ELSE t.totalBiaya END as biayaHitung "
                   + "FROM tiket t JOIN kendaraan k ON t.kendaraan = k.platNomor";
        java.sql.Statement stm = conn.createStatement();
        ResultSet rs = stm.executeQuery(sql);

        while (rs.next()) {
            String waktuKeluar = rs.getString("waktuKeluar");
            String statusKeluar = (waktuKeluar != null) ? waktuKeluar : "(masih parkir)";

            model.addRow(new Object[]{
                rs.getString("idTiket"),
                rs.getString("kendaraan"),
                rs.getString("jenis"),
                rs.getString("waktuMasuk"),
                statusKeluar,
                rs.getString("durasi") + " jam",
                "Rp " + rs.getString("biayaHitung")
            });
        }
        jTable1.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error load table: " + e.getMessage());
    }
}

}
