/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tubespbo.gui;

import com.mycompany.tubespbo.classs.*;
import com.mycompany.tubespbo.gui.Utama;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
/**
 *
 * @author fathi
 */
public class Masuk extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Masuk.class.getName());
    
    private static Connection mysqlconfig;

public static Connection configDB() {
    try {
        String url = "jdbc:mysql://localhost:3306/datapark";
        String user = "root";
        String pass = "";
        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        mysqlconfig = DriverManager.getConnection(url, user, pass);
    } catch (SQLException e) {
        System.err.println("koneksi gagal " + e.getMessage());
    }
    return mysqlconfig;
}

    /**
     * Creates new form Masuk
     */
    public Masuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("KENDARAAN MASUK");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Plat Nomor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Merk");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Jenis");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor", "Mobil" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jButton1.setText("Masuk");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Baru");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Kembali");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jComboBox1, 0, 233, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3)
                        .addGap(82, 82, 82)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        String platNomor = jTextField1.getText().trim();
        String merk = jTextField2.getText().trim();
        String jenis = jComboBox1.getSelectedItem().toString();

        if (platNomor.isEmpty() || merk.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Plat Nomor dan Merk tidak boleh kosong!");
            return;
        }

        // OOP: buat object Kendaraan
        Kendaraan kendaraan;
        if (jenis.equalsIgnoreCase("Motor")) {
            kendaraan = new Motor(platNomor, merk);
        } else {
            kendaraan = new Mobil(platNomor, merk);
        }

        Connection conn = com.mycompany.tubespbo.TubesPbo.getInstance();

        String cekSql = "SELECT * FROM kendaraan WHERE platNomor = ?";
        PreparedStatement cekPst = conn.prepareStatement(cekSql);
        cekPst.setString(1, kendaraan.getPlatNomor());
        ResultSet cekRs = cekPst.executeQuery();

        if (!cekRs.next()) {
            String sqlKendaraan = "INSERT INTO kendaraan (platNomor, merk, jumlahRoda, jenis) VALUES (?, ?, ?, ?)";
            PreparedStatement pstKendaraan = conn.prepareStatement(sqlKendaraan);
            pstKendaraan.setString(1, kendaraan.getPlatNomor());
            pstKendaraan.setString(2, kendaraan.getMerk());
            pstKendaraan.setInt(3, kendaraan.getJumlahRoda());
            pstKendaraan.setString(4, jenis);
            pstKendaraan.execute();
        }

        // OOP: buat object SlotParkir
        String sqlSlot = "SELECT idSlot, status, jenisSlot FROM slotParkir WHERE status = false AND jenisSlot = ? LIMIT 1";
        PreparedStatement pstSlot = conn.prepareStatement(sqlSlot);
        pstSlot.setString(1, jenis);
        ResultSet rsSlot = pstSlot.executeQuery();

        if (!rsSlot.next()) {
            JOptionPane.showMessageDialog(this, "Slot " + jenis + " penuh!");
            return;
        }

        SlotParkir slot = new SlotParkir(
            rsSlot.getString("idSlot"),
            rsSlot.getBoolean("status"),
            rsSlot.getString("jenisSlot")
        );

        // OOP: buat object Tiket
        String idTiket = "TKT" + System.currentTimeMillis();
        Tiket tiket = new Tiket(idTiket, kendaraan, slot, java.time.LocalDateTime.now());

        String sqlTiket = "INSERT INTO tiket (idTiket, kendaraan, slot, waktuMasuk) VALUES (?, ?, ?, NOW())";
        PreparedStatement pstTiket = conn.prepareStatement(sqlTiket);
        pstTiket.setString(1, tiket.getIdTiket());
        pstTiket.setString(2, kendaraan.getPlatNomor());
        pstTiket.setString(3, slot.getIdSlot());
        pstTiket.execute();

        slot.setStatus(true);
        String sqlUpdateSlot = "UPDATE slotParkir SET status = true WHERE idSlot = ?";
        PreparedStatement pstUpdateSlot = conn.prepareStatement(sqlUpdateSlot);
        pstUpdateSlot.setString(1, slot.getIdSlot());
        pstUpdateSlot.execute();

        JOptionPane.showMessageDialog(this, "Kendaraan masuk!\nSlot: " + slot.getIdSlot() + "\nID Tiket: " + tiket.getIdTiket());
        kosong();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Masuk().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void kosong() {
    jTextField1.setText("");
    jTextField2.setText("");
    jComboBox1.setSelectedIndex(0);
}   
}

